"""empty message

Revision ID: 19d5f285523f
Revises: 0e331a434184
Create Date: 2016-05-31 21:37:11.086685

"""

# revision identifiers, used by Alembic.
revision = '19d5f285523f'
down_revision = '0e331a434184'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
